### ISSUE TITLE
Mettre à jour LICENSE pour OSUMontreal and contributors

### ISSUE THREAD

**Issue by SamGuay** [osumontreal/docs.osumontreal.ca#16]
Au lieu de Samuel Guay et Danny Colin, mettre *OSUMontreal and contributors* comme sur tous les autres repos.

**Comment by dannycolin** [comment]
Fixed via [commit 5701278](https://github.com/osumontreal/docs.osumontreal.ca/commit/5701278a0a63fa3e7340e61abf08ed21257d8885).
